lib/rubocop/cop/betterment/memoization_with_arguments.rb, spec/rubocop/cop/betterment/memoization_with_arguments_spec.rb
/domain @effron
/platform @smudge 
Sometimes default values are set in the 'initialize' method via `@foo ||= true`, and in this case there isn't a concern for stale ivar values considering that 'initialize' is only run once per instance. So this change adds an exception for `initialize` methods to the rule.
For example, with ActiveModel we might do something like:
```ruby
class Person
include ActiveModel::Model
attr_accessor :id, :name, :omg
def initialize(attributes = {})
super
@omg ||= true
end
end
```
([example from the Rails docs](https://api.rubyonrails.org/classes/ActiveModel/Model.html))
=> Allow memoization patterns in 'initialize' methods

betterlint.gemspec, lib/rubocop/cop/betterment/active_job_performable.rb, spec/rubocop/cop/betterment/active_job_performable_spec.rb, spec/rubocop/cop/betterment/allowlist_blocklist_spec.rb, spec/rubocop/cop/betterment/authorization_in_controller_spec.rb, spec/rubocop/cop/betterment/dynamic_params_spec.rb, spec/rubocop/cop/betterment/memoization_with_arguments_spec.rb, spec/rubocop/cop/betterment/unsafe_job_spec.rb, spec/rubocop/cop/betterment/unscoped_find_spec.rb, spec/rubocop/cop/betterment/utils/parser_spec.rb
The following code was incorrectly being recognized as an offense:
```ruby
class MyBusinessLogic
class MyJob < ApplicationJob
def perform
MyBusinessLogic.call
end
end
end
```
This was happening because `Node#descendants` returns all of the nodes descendants (recursively), rather than the node's immediate children.
=> Fix false positives from ActiveJobPerformable

betterlint.gemspec, lib/rubocop/cop/betterment/hardcoded_id.rb
Should fix:
```
An error occurred while Betterment/HardcodedID cop...
wrong number of arguments (given 1, expected 0; required keyword: range)
/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rubocop-1.23.0/lib/rubocop/cop/mixin/range_help.rb:54:in `range_with_surrounding_space'
```
=> Update range_with calls to pass range parameter

betterlint.gemspec, config/default.yml, lib/rubocop/cop/betterment/implicit_redirect_type.rb, lib/rubocop/cop/betterment/non_standard_actions.rb, lib/rubocop/cop/betterment/spec_helper_required_outside_spec_dir.rb, lib/rubocop/cop/betterment/unscoped_find.rb
Based on feedback from an automated linter fix from `rubocop-rspec` v2.7 (https://github.com/Betterment/test_track/pull/182#discussion_r1117806216), creating this PR to start a conversation around disabling the rule for apps that depend on this gem going forward. 
[Docs for the rule being disabled](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/SyntaxMethods)
/cc: @smudge
=> feat(rubocop-rspec): disable FactoryBot SyntaxMethods rule

betterlint.gemspec, config/default.yml, lib/rubocop/cop/betterment/non_standard_actions.rb, lib/rubocop/cop/betterment/site_prism_loaded.rb, lib/rubocop/cop/betterment/unscoped_find.rb
The `Style/IfUnlessModifier` encourages us to use the modifier form of if or unless.
```ruby
if ready?
perform_action!
end
perform_action! if ready?
```
Generally, I think most people agree with this. However, our `Layout/LineLength` is set to a very generous 140. So, Rubocop would also encourage us to put this on one line:
```ruby
unless user.profile_configuration.ready?
redirect_to user_profile_configuration_path, flash: { error: "We're setting up your profile." }
end
redirect_to user_profile_configuration_path, flash: { error: "We're setting up your profile." } unless user.profile_configuration.ready?
```
As a reader, these conditionals are the most important thing for me to see. I think we should leave the decision to use a modifier up to the author.
=> Disable Style/IfUnlessModifier

betterlint.gemspec, config/default.yml
This is really annoying:
```
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
* rubocop-capybara (https://rubygems.org/gems/rubocop-capybara)
You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
=> Disable new cop suggestions

.github/workflows/tests.yml, .rubocop.yml, betterlint.gemspec, config/default.yml, lib/rubocop/cop/betterment/utils/parser.rb
betterlint-1.4.4/config/default.yml: RSpec/FactoryBot/SyntaxMethods has the wrong namespace - should be FactoryBot
=> Fix warning when running betterlint

betterlint.gemspec, config/default.yml
This was causing hundreds of additions to our rubocop-todo files, and doesn't feel like a worthwhile style to enforce (we don't enforce paren consistency elsewhere).
I haven't had any issues with churn in our factory bot parens usages, and this cop is missing the reasonable config of being able to have single arg factory bot calls without parens. 
I think we should disable this until we have an easier way to autoformat consistently.
/no-platform
=> Exclude FactoryBot/ConsistentParenthesesStyle

betterlint.gemspec, config/default.yml
/no-platform
Disable a couple of new RSpec cops that have a lot of violations in our codebase and provide questionable or marginable value.
IndexedLet prevents numbers at the end of let variables. I think there are valid cases where using numbers is fine, and I can't say I've encountered specs where the use of them has impeded my ability to understand what's happening.
BeEq flags cases where `be eq` is used instead of just `be` when `be` would work. In ruby we rarely use identity based equality, and I think using it here simply because we can will lead to more confusion and bugs then sticking with `eq`. I personally would restrict use of `be` to specific cases where the identity of the object matters, like when we care about a particular instance of an object being returned.
=> Disable RSpec/IndexedLet and RSpec/BeEq

config/default.yml
This branch changes the numbered parameters feature to **not** be allowed. We [discussed this](https://betterment.slack.com/archives/C5PL74XGV/p1692719844839739) and decided it did not provide enough value for the confusion it may cause.
So, instead of this, using the _implicit_ numbered parameter `_1`:
```ruby
[1, 2, 3].map { _1 * 2 }
```
We should write this, using an _explicit_ variable in the block:
```ruby
[1, 2, 3].map { |i| i * 2 }
```
=> Change Style/NumberedParameters cop to be disallowed

config/default.yml, lib/rubocop/cop/betterment/unscoped_find.rb
/domain @smudge @effron @willlockwood
/platform @Betterment/ruby-platform-reviewers
This branch enables the Layout/ClosingParenthesisIndentation cop which was curiously disabled in the initial creation of betterlint.
=> Change Layout/ClosingParenthesisIndentation to be enabled

lib/rubocop/cop/betterment/unscoped_find.rb, spec/rubocop/cop/betterment/unscoped_find_spec.rb
Currently, the `UnscopedFind` cop currently identifies violations of trust-root-chaining by looking for different types of custom finds that contain "user input"—specifically, that a non-trust-root-chained find contains a direct or indirect reference to `params`. For ruby applications using GraphQL, this cop will almost never find violations, since GraphQL implementations will idiomatically have no reference to `params`.
Here, I'm attempting to bridge the `UnscopedFind` gap for GraphQL implementations by also considering relevant find nodes in violation with the cop when inside of a namespace matching "graphql". Since popular packages like `graphql-ruby` promote the usage of `GraphQL` namespaces, I think this is the highest-fidelity fix I can imagine to expand the relevance of this cop …
=> feat: Expand `UnscopedFind` offenses in "graphql" namespaces

betterlint.gemspec
This PR updates the betterlint version to `1.7.0` to include #29 and #30 in a new gem release.
=> chore: Update version to `1.7.0`

Gemfile.lock, betterlint.gemspec, lib/rubocop/cop/betterment/redirect_status.rb, lib/rubocop/cop/betterment/render_status.rb, lib/rubocop/cop/betterment/utils/response_status.rb, spec/rubocop/cop/betterment/redirect_status_spec.rb, spec/rubocop/cop/betterment/render_status_spec.rb
* Handle `render` or `redirect_to` with parentheses
* Handle `render` or `redirect_to` with no arguments
=> Fix edge cases in status code autocorrection

betterlint.gemspec
Metadata will help people on RubyGems.org, or other library indexers, to find the source code, issue tracker, CHANGELOG, etc
=> Add homepage & metadata to betterlint.gemspec

Gemfile.lock, betterlint.gemspec, config/default.yml, lib/rubocop/cop/betterment/authorization_in_controller.rb, lib/rubocop/cop/betterment/utils/parser.rb
The default (17) is pretty restrictive, and sometimes feels inconsistent.
We've seen a few negative consequences of enforcing this AbcSize:
1. People often extract local variables to memoized private methods. This is not desirable, because a local variable actually has a lower cognitive overhead than a memoized, private method.
2. By extracting lots of small, private methods, you're adding more indirection and literally more lines of code to read. Sometimes, this can make it harder to read and understand code.
3. By eagerly extracting lots of small, private methods, you might be making it harder to identify more effective ways of refactoring the code.
We want to lean on code reviewers to raise a concern when code becomes overly complex.
/no-platform
=> Make Metrics/AbcSize much more liberal

Gemfile.lock, betterlint.gemspec, config/default.yml
**Summary of changes**:
Per a conversation in Slack we don't seem to have strong opinions about this, so disabling this cop here for all our projects using Betterlint.
=> feat: disable factory bot association cop by default

Gemfile, Gemfile.lock, betterlint.gemspec, config/default.yml, lib/rubocop/cop/betterment/non_standard_actions.rb, lib/rubocop/cop/betterment/render_status.rb, lib/rubocop/cop/betterment/utils/parser.rb, spec/standard_compliance_spec.rb, spec/support/betterlint_config.rb
In an effort to more closely adhere to https://github.com/standardrb/standard, I've added a spec to detect the introduction of new rules that don't comply with Standard.
I've updated the layout cops to more closely match the rules in standard.
=> Update `Layout` cops to be more consistent with Standard

Gemfile.lock, betterlint.gemspec, config/default.yml, spec/standard_compliance_spec.rb
Rubocop [changed the default](https://github.com/rubocop/rubocop/pull/13300) for `Style/HashSyntax`'s `EnforcedShorthandSyntax` configuration from `always` to `either`.  This reverts that change in `BetterLint` by explicitly setting the value to `either`.
This is not in line with `Standard`'s config, so I added an exception.
I prefer a consistent enforcement style so we don't have any pull-request discussion on whether or not to expand/contract hash syntax. The shorthand syntax also has fewer rooms for typos and makes it more obvious when there are subtle name differences between hash keys and values.
=> Set enforced shorthand syntax to always

Gemfile.lock, betterlint.gemspec
This change increases the version number so we can publish [a recent update](https://github.com/Betterment/betterlint/pull/47) to RubyGems.
=> feat: increase version to 1.21.0
